# Learning PyTorch

In [1]:
import torch

# Creating 
x = torch.Tensor([5,3])
y = torch.Tensor([2,1])

print (x*y)


tensor([10.,  3.])


In [2]:
x = torch.zeros([2,5])

In [3]:
print(x)

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])


In [4]:
x.shape

torch.Size([2, 5])

In [5]:
y = torch.rand([2,5])

In [6]:
y

tensor([[0.4451, 0.5097, 0.5191, 0.4358, 0.9385],
        [0.7873, 0.6845, 0.3203, 0.2736, 0.5015]])

In [7]:
# Reshing in PyTorch
y.view([1,10])

tensor([[0.4451, 0.5097, 0.5191, 0.4358, 0.9385, 0.7873, 0.6845, 0.3203, 0.2736,
         0.5015]])

In [8]:
y

tensor([[0.4451, 0.5097, 0.5191, 0.4358, 0.9385],
        [0.7873, 0.6845, 0.3203, 0.2736, 0.5015]])

In [9]:
y = y.view([1,10])

In [10]:
y

tensor([[0.4451, 0.5097, 0.5191, 0.4358, 0.9385, 0.7873, 0.6845, 0.3203, 0.2736,
         0.5015]])

# Working with Data

In [13]:
# Load Libraries

import torch
import torchvision
from torchvision import transforms, datasets

# pip install torchvision